# Generated by Django 3.2.3 on 2021-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesInputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('columns', models.TextField(default='')),
                ('data', models.TextField(default='')),
            ],
        ),
    ]
