# Generated by Django 3.2.3 on 2021-06-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesinputdata',
            name='file',
            field=models.TextField(default=''),
        ),
    ]
