# Generated by Django 3.2.3 on 2021-06-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicesinputdata_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesinputdata',
            old_name='file',
            new_name='filename',
        ),
    ]
