# Generated by Django 3.2.3 on 2021-06-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_file_servicesinputdata_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesinputdata',
            old_name='data',
            new_name='values',
        ),
    ]
