# Generated by Django 3.2.3 on 2021-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_servicesinputdata_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesfilesinformations',
            name='coords_columns',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicesfilesinformations',
            name='infos_columns',
            field=models.TextField(default=''),
        ),
    ]
