# Generated by Django 3.2.3 on 2021-07-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vehiclesinputdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesfilesinformations',
            name='key_column',
            field=models.TextField(default=''),
        ),
    ]
